### ISSUE TITLE
Not triggered when resizing with keyboard shortcuts

### ISSUE THREAD

**Issue by Yajo** [hermes83/compiz-alike-windows-effect#1]
When using <kbd>Super</kbd> + <kbd>:arrow_up: / :arrow_down: / :arrow_left: / :arrow_right:</kbd>, the effect doesn't happen.

**Comment by Yajo** [comment]
any explanation for closing? :roll_eyes:

**Comment by hermes83** [comment]
> any explanation for closing? roll_eyes

I solved the problem and then closed it.
Thanks for the tip
