### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by stuaxo** [hermes83/compiz-alike-windows-effect#14]
I'm a longtime fan of windows that wobble, but also a gnome user, so this is great.

There was a previous extension, but the behaviour seemed a little buggy, this is much closer to the original wobbly windows.

Thanks for making the desktop fun again (I don't think usability + fun have to be mutually exclusive).

**Comment by hermes83** [comment]
You are very welcome, Thanks for the encouraging words!

**Comment by stuaxo** [comment]
If there was a patreon or librepay for I would consider chucking something your way, I can't be the only one (even if the community is probaby small).
