### ISSUE TITLE
Improvement - ignore maximize effect when fullscreening windows

### ISSUE THREAD

**Issue by ninja-** [hermes83/compiz-alike-windows-effect#16]
It would be nice if we could detect when window is going fullscreen(for example when doing F11 in chrome, or fullscreening some video) and cancel the effect, because currently it just looks buggy, that would be a nice improvement.
I know that I can disable maximize effect in settings...

**Comment by hermes83** [comment]
Dear @ninja- 
the commit should fix the issue. 
Please note that it is not released in gnome extension portal
