### ISSUE TITLE
Glitchy resize

### ISSUE THREAD

**Issue by MichalLebeda** [hermes83/compiz-alike-windows-effect#17]
this is related to wayland on gnome shell 3.38

When maximizing, there is a small gap on the right for about 2 seconds after size change. When I disable maximize effect, the window freezes with small glitch and then jumps to maximized state. 
(better seen on dark background)
![Screenshot from 2020-10-22 17-33-56](https://user-images.githubusercontent.com/5246963/96896082-64dbc200-148d-11eb-8c90-4baeeb62ebaa.png)

**Comment by hermes83** [comment]
First of all, hello

Please try to clean up the contents of all the vfunc_deform_vertex methods inside the effects.js file:

```javascript
vfunc_deform_vertex(w, h, v) {}
```

After that logout of the gnome session and login again.
Than try to repeat the operation with a window of the same application used in your screenshot.

If the problem persists, you should open an issue to the gnome project. 
In fact, in this case the extension should not change the shape of your window in any way (the window clipping would be done arbitrarily by Clutter).

Please let me know.

**Comment by hermes83** [comment]
Please try to clean up the contents of all the vfunc_deform_vertex methods inside the effects.js file:

```javascript
vfunc_deform_vertex(w, h, v) {}
```

After that logout of the gnome session and login again.
Than try to repeat the operation with a window of the same application used in your screenshot.

If the problem persists, you should open an issue to the gnome project.
In fact, in this case the extension should not change the shape of your window in any way (the window clipping would be done arbitrarily by Clutter).

Please let me know.

**Comment by MichalLebeda** [comment]
Works fine without glitches. Effect is of course absent but no glitches

**Comment by MichalLebeda** [comment]
first I thought it is fine but it really isn't. The 1px line is still there and disappear in 1-2s.

**Comment by MichalLebeda** [comment]
I have found out that not all apps are affected. There is a small list of those which are: All jetbrains based products, VSCode, Kitty terminal, Blender. **NOT** affected: Nautilus, Tweak Tool. It really seem that only apps on xwayland are affected. I have to say that this glitch is not present when the extension is off.

**Comment by hermes83** [comment]
Thank you, can you try my first suggestion?
Please let me know

**Comment by fegasi** [comment]
Hello! Actually, I figured out that this is a theme problem. So you can check more of this here: https://askubuntu.com/questions/1206023/extra-padding-on-right-of-the-scrollbar-on-gnome-terminal-when-in-vanilla-sessio and here https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/206837.

**Comment by fegasi** [comment]
Hello! Actually, I figured out that this is a theme problem. So you can check more of this here: https://bugzilla.gnome.org/show_bug.cgi?id=123408.
