### ISSUE TITLE
Add the posibility to only use the resizing effect ?

### ISSUE THREAD

**Issue by rcmz** [hermes83/compiz-alike-windows-effect#20]
Hello, I like the resizing effect but not the window moving effect. Would it be possible to add toggles to only activate one or the other ?

**Comment by hermes83** [comment]
Hi @rcmz, the request seems plausible to me. The new development is progress

**Comment by rcmz** [comment]
Great 😀

**Comment by hermes83** [comment]
released on [gnome extensions portal](https://extensions.gnome.org/extension/2950/compiz-alike-windows-effect)

**Comment by rcmz** [comment]
awesome thanks !
