### ISSUE TITLE
Can't set spring effect to 0

### ISSUE THREAD

**Issue by giedriusStan** [hermes83/compiz-alike-windows-effect#4]
Hey, this is my favorite extension now, but I'd like to be able to disable the spring effect, for some reason I can't do that anymore after most recent update. The lowest it can go is setting 1, can we please also have a setting for 0?

![image](https://user-images.githubusercontent.com/1705190/83158905-0e509e80-a10e-11ea-9f27-ff0774b16944.png)

**Comment by hermes83** [comment]
Thanks @giedriusStan, the required fix will be released on the gnome extensions portal in the next few days.

**Comment by hermes83** [comment]
fix released
