### ISSUE TITLE
Would you be interested in maintaining libanimation?

### ISSUE THREAD

**Issue by smspillaz** [hermes83/compiz-alike-windows-effect#5]
Hi,

(I'm the original author of libanimation),

It seems likely to me that Endless won't be maintaining libanimation into the future (the wobbly effect was removed from the shell etc quite some time ago). I had hoped to port over a few of the other animations to libanimation and started work on a [shell extension](https://github.com/endlessm/libanimation/pull/10) but never really got the opportunity to finish the work on that.

Since you seem interested in the library and it appears to still work (yay!), would you be interested in collaborating on this?

**Comment by hermes83** [comment]
Dear @smspillaz with libanimation you are my hero.
I regret hearing the Endless decision about libanimation (it makes me smile the contrast between the company name and the decision to end the contribution).

Unfortunately, I don't think I'm the right partner for maintaining the library.
My technological background, and work commitments, would prevent me from making a valuable contribution (libanimation deserves something better).

I don't know if I will develop any further solutions in a not well-defined future, I would be happy if these and the current ones could be of any use for libanimation.

**Comment by stuaxo** [comment]
I can definitely echo both sentiments, thanks so much for libanimation, and at the same time I don't have the time/skills I'd like to offer to pick it up.

What would a good a path be to keep libanimation alive ?

I wonder if compiz itself would be interested in moving to the external libanimation (I'm not quite sure the amount of work involved) ?

**Comment by danigm** [comment]
I'm currently working on the wobbly windows effect on the Endless OS and I've followed this work and the problems with libanimation maintenance.

I only want to tell you that I'll give some love to libanimation, so I'll start to review the current PRs and update what's needed there.

**Comment by smspillaz** [comment]
My PRs probably need some love 😅

**Comment by stuaxo** [comment]
@danigm is there an aim to make libanimation a part of upstream GNOME in future?

**Comment by danigm** [comment]
> @danigm is there an aim to make libanimation a part of upstream GNOME in future?

No, libanimation doesn't have a lot of functionality that could be integrated upstream. I can't think about a core gnome-shell functionality that uses the wobbly effect right now. I think this should continue to be an external library.
