### ISSUE TITLE
Resize animation tiles

### ISSUE THREAD

**Issue by WuerfelDev** [hermes83/compiz-alike-windows-effect#6]
I didn't like the resize animation because the tiles are too big. Could you set higher default values for `set_n_tiles` or at least make it configurable via prefs? 
I found the values (10, 10) are fine for me.
https://github.com/hermes83/compiz-alike-windows-effect/blob/master/effects.js#L71

Here's the difference on a horizontal resize:
(6, 4) | (10, 10)
---- | ----
![Screenshot from 2020-06-23 17-11-10](https://user-images.githubusercontent.com/12686819/85422051-6fd12500-b575-11ea-8c68-6904c057284a.png) | ![Screenshot from 2020-06-23 17-09-08](https://user-images.githubusercontent.com/12686819/85422070-752e6f80-b575-11ea-8fac-efe4eab27ab3.png)

**Comment by hermes83** [comment]
Fix applied, added parameters as suggested.
