### ISSUE TITLE
Problem with HiDPI

### ISSUE THREAD

**Issue by johnfactotum** [hermes83/compiz-alike-windows-effect#7]
When using HiDPI, moving the window by dragging the left part of the titlebar (or by dragging the left part of the window, by holding <kbd>Super</kbd>) causes vertical spikes on the top left corer. Something seems off when dragging on right side of the window as well, though it's less noticeable.

**Comment by hermes83** [comment]
Dear @johnfactotum,
I tried to replicate the issue you report without success. Is there any chance to get a short video about it?

**Comment by johnfactotum** [comment]
With scale set to 125%, dragging by the left side of the window results in this:
![Peek 2020-07-15 09-25](https://user-images.githubusercontent.com/50942278/87492564-55510f80-c63a-11ea-884c-c1f56dec0fd4.gif)
The top left corner seems off; it doesn't follow the cursor, instead it jumps erratically.

When dragging by the right side of the window, things seem to be working more as expected:
![Peek 2020-07-15 09-26](https://user-images.githubusercontent.com/50942278/87492590-6732b280-c63a-11ea-8776-028311cfcba6.gif)

When scale is set to 100%, the top left corner no longer moves erratically:
![Peek 2020-07-15 09-37](https://user-images.githubusercontent.com/50942278/87493237-e07ed500-c63b-11ea-999a-b03e7c008ffd.gif)

**Comment by hermes83** [comment]
Thanks @johnfactotum , 
the commit should fix the issue.
It will be released on the gnome extension portal in the next few days
