### ISSUE TITLE
Feature request: Disable wobble animation on full screen and minimise animations.

### ISSUE THREAD

**Issue by osirase** [hermes83/compiz-alike-windows-effect#8]
I mainly notice then when in Firefox I enable the fullscreen on a youtube video it has a sort of jittery animation trigger. I think the default gnome animations for maximise and minimise are more desirable, leaving the wobbly part for just dragging the windows around.

**Comment by hermes83** [comment]
Ciao @osirase ,
from the settings window you can disable the effect when the window is maximized (highlighted in red), when it is resized (in yellow) and set the quality of the effect (in green):

![settings](https://user-images.githubusercontent.com/7895800/87437625-df738680-c5ee-11ea-8af6-728a86240f64.png)

I suppose it is enough to customize the extension. Do you think there are problems in their use that I don't catch?

**Comment by osirase** [comment]
Perfect! Thanks for that :) No other problems I can think of here.
